-- Country data (all 249 countries)
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AF', 'Afghanistan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AL', 'Albania');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('DZ', 'Algeria');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AS', 'American Samoa');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AD', 'Andorra');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AO', 'Angola');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AI', 'Anguilla');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AQ', 'Antarctica');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AG', 'Antigua and Barbuda');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AR', 'Argentina');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AM', 'Armenia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AW', 'Aruba');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AU', 'Australia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AT', 'Austria');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AZ', 'Azerbaijan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BS', 'Bahamas');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BH', 'Bahrain');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BD', 'Bangladesh');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BB', 'Barbados');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BY', 'Belarus');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BE', 'Belgium');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BZ', 'Belize');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BJ', 'Benin');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BM', 'Bermuda');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BT', 'Bhutan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BO', 'Bolivia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BQ', 'Bonaire');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BA', 'Bosnia and Herzegovina');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BW', 'Botswana');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BV', 'Bouvet Island');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BR', 'Brazil');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('IO', 'British Indian Ocean Territory');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BN', 'Brunei Darussalam');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BG', 'Bulgaria');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BF', 'Burkina Faso');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BI', 'Burundi');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CV', 'Cabo Verde');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KH', 'Cambodia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CM', 'Cameroon');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CA', 'Canada');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KY', 'Cayman Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CF', 'Central African Republic');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TD', 'Chad');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CL', 'Chile');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CN', 'China');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CX', 'Christmas Island');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CC', 'Cocos Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CO', 'Colombia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KM', 'Comoros');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CG', 'Congo');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CD', 'Congo Democratic Republic');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CK', 'Cook Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CR', 'Costa Rica');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CI', 'Cote d Ivoire');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('HR', 'Croatia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CU', 'Cuba');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CW', 'Curacao');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CY', 'Cyprus');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CZ', 'Czechia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('DK', 'Denmark');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('DJ', 'Djibouti');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('DM', 'Dominica');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('DO', 'Dominican Republic');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('EC', 'Ecuador');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('EG', 'Egypt');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SV', 'El Salvador');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GQ', 'Equatorial Guinea');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ER', 'Eritrea');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('EE', 'Estonia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SZ', 'Eswatini');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ET', 'Ethiopia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('FK', 'Falkland Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('FO', 'Faroe Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('FJ', 'Fiji');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('FI', 'Finland');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('FR', 'France');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GF', 'French Guiana');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PF', 'French Polynesia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TF', 'French Southern Territories');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GA', 'Gabon');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GM', 'Gambia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GE', 'Georgia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('DE', 'Germany');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GH', 'Ghana');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GI', 'Gibraltar');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GR', 'Greece');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GL', 'Greenland');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GD', 'Grenada');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GP', 'Guadeloupe');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GU', 'Guam');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GT', 'Guatemala');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GG', 'Guernsey');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GN', 'Guinea');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GW', 'Guinea-Bissau');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GY', 'Guyana');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('HT', 'Haiti');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('HM', 'Heard Island');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('VA', 'Holy See');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('HN', 'Honduras');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('HK', 'Hong Kong');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('HU', 'Hungary');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('IS', 'Iceland');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('IN', 'India');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ID', 'Indonesia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('IR', 'Iran');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('IQ', 'Iraq');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('IE', 'Ireland');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('IM', 'Isle of Man');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('IL', 'Israel');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('IT', 'Italy');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('JM', 'Jamaica');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('JP', 'Japan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('JE', 'Jersey');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('JO', 'Jordan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KZ', 'Kazakhstan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KE', 'Kenya');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KI', 'Kiribati');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KP', 'Korea North');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KR', 'Korea South');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KW', 'Kuwait');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KG', 'Kyrgyzstan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LA', 'Lao');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LV', 'Latvia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LB', 'Lebanon');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LS', 'Lesotho');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LR', 'Liberia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LY', 'Libya');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LI', 'Liechtenstein');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LT', 'Lithuania');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LU', 'Luxembourg');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MO', 'Macao');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MK', 'Macedonia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MG', 'Madagascar');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MW', 'Malawi');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MY', 'Malaysia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MV', 'Maldives');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ML', 'Mali');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MT', 'Malta');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MH', 'Marshall Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MQ', 'Martinique');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MR', 'Mauritania');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MU', 'Mauritius');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('YT', 'Mayotte');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MX', 'Mexico');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('FM', 'Micronesia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MD', 'Moldova');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MC', 'Monaco');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MN', 'Mongolia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ME', 'Montenegro');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MS', 'Montserrat');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MA', 'Morocco');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MZ', 'Mozambique');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MM', 'Myanmar');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NA', 'Namibia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NR', 'Nauru');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NP', 'Nepal');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NL', 'Netherlands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NC', 'New Caledonia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NZ', 'New Zealand');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NI', 'Nicaragua');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NE', 'Niger');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NG', 'Nigeria');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NU', 'Niue');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NF', 'Norfolk Island');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MP', 'Northern Mariana Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('NO', 'Norway');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('OM', 'Oman');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PK', 'Pakistan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PW', 'Palau');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PS', 'Palestine');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PA', 'Panama');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PG', 'Papua New Guinea');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PY', 'Paraguay');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PE', 'Peru');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PH', 'Philippines');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PN', 'Pitcairn');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PL', 'Poland');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PT', 'Portugal');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PR', 'Puerto Rico');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('QA', 'Qatar');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('RE', 'Reunion');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('RO', 'Romania');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('RU', 'Russian Federation');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('RW', 'Rwanda');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('BL', 'Saint Barthelemy');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SH', 'Saint Helena');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('KN', 'Saint Kitts and Nevis');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LC', 'Saint Lucia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('MF', 'Saint Martin');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('PM', 'Saint Pierre and Miquelon');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('VC', 'Saint Vincent and the Grenadines');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('WS', 'Samoa');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SM', 'San Marino');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ST', 'Sao Tome and Principe');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SA', 'Saudi Arabia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SN', 'Senegal');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('RS', 'Serbia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SC', 'Seychelles');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SL', 'Sierra Leone');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SG', 'Singapore');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SX', 'Sint Maarten');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SK', 'Slovakia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SI', 'Slovenia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SB', 'Solomon Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SO', 'Somalia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ZA', 'South Africa');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GS', 'South Georgia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SS', 'South Sudan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ES', 'Spain');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('LK', 'Sri Lanka');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SD', 'Sudan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SR', 'Suriname');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SJ', 'Svalbard and Jan Mayen');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SE', 'Sweden');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('CH', 'Switzerland');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('SY', 'Syrian Arab Republic');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TW', 'Taiwan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TJ', 'Tajikistan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TZ', 'Tanzania');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TH', 'Thailand');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TL', 'Timor-Leste');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TG', 'Togo');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TK', 'Tokelau');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TO', 'Tonga');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TT', 'Trinidad and Tobago');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TN', 'Tunisia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TR', 'Turkey');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TM', 'Turkmenistan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TC', 'Turks and Caicos Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('TV', 'Tuvalu');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('UG', 'Uganda');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('UA', 'Ukraine');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AE', 'United Arab Emirates');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('GB', 'United Kingdom');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('US', 'United States');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('UM', 'United States Minor Outlying Islands');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('UY', 'Uruguay');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('UZ', 'Uzbekistan');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('VU', 'Vanuatu');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('VE', 'Venezuela');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('VN', 'Viet Nam');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('VG', 'Virgin Islands British');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('VI', 'Virgin Islands US');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('WF', 'Wallis and Futuna');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('EH', 'Western Sahara');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('YE', 'Yemen');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ZM', 'Zambia');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('ZW', 'Zimbabwe');
MERGE INTO country (co_code, co_name) KEY(co_code) VALUES ('AX', 'Aland Islands');

-- Department data
MERGE INTO department (dp_id, dp_name) KEY(dp_id) VALUES (1, 'HR');
MERGE INTO department (dp_id, dp_name) KEY(dp_id) VALUES (2, 'Engineering');
MERGE INTO department (dp_id, dp_name) KEY(dp_id) VALUES (3, 'Marketing');
MERGE INTO department (dp_id, dp_name) KEY(dp_id) VALUES (4, 'Finance');

-- Employee data
MERGE INTO employee (em_id, em_name, em_salary, em_dp_id) KEY(em_id) VALUES (1, 'John Smith', 75000.00, 2);
MERGE INTO employee (em_id, em_name, em_salary, em_dp_id) KEY(em_id) VALUES (2, 'Jane Doe', 82000.00, 2);
MERGE INTO employee (em_id, em_name, em_salary, em_dp_id) KEY(em_id) VALUES (3, 'Alice Johnson', 65000.00, 1);
MERGE INTO employee (em_id, em_name, em_salary, em_dp_id) KEY(em_id) VALUES (4, 'Bob Wilson', 70000.00, 3);
MERGE INTO employee (em_id, em_name, em_salary, em_dp_id) KEY(em_id) VALUES (5, 'Carol Brown', 90000.00, 4);

-- Skill data
MERGE INTO skill (sk_id, sk_name) KEY(sk_id) VALUES (1, 'Java');
MERGE INTO skill (sk_id, sk_name) KEY(sk_id) VALUES (2, 'Spring');
MERGE INTO skill (sk_id, sk_name) KEY(sk_id) VALUES (3, 'SQL');
MERGE INTO skill (sk_id, sk_name) KEY(sk_id) VALUES (4, 'Python');
MERGE INTO skill (sk_id, sk_name) KEY(sk_id) VALUES (5, 'Communication');

-- Employee-Skill mapping
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (1, 1);
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (1, 2);
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (1, 3);
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (2, 1);
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (2, 4);
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (3, 5);
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (4, 5);
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (4, 3);
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (5, 3);
MERGE INTO employee_skill (es_em_id, es_sk_id) KEY(es_em_id, es_sk_id) VALUES (5, 4);

-- Stock data: Facebook September 2019
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-03', 184.00, 182.39, 9779400);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-04', 184.65, 187.14, 11308000);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-05', 188.53, 190.90, 13876700);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-06', 190.21, 187.49, 15226800);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-09', 187.73, 188.76, 14722400);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-10', 187.44, 186.17, 15455900);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-11', 186.46, 188.49, 11761700);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-12', 189.86, 187.47, 11419800);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-13', 187.33, 187.19, 11441100);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-16', 186.93, 186.22, 8444800);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-17', 186.66, 188.08, 9671100);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-18', 188.09, 188.14, 9681900);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-19', 188.66, 190.14, 10392700);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-20', 190.66, 189.93, 19934200);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-23', 189.34, 186.82, 13327600);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-24', 187.98, 181.28, 18546600);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-25', 181.45, 182.80, 18068300);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-26', 181.33, 180.11, 16083300);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-09-27', 180.49, 177.10, 14656200);

-- Facebook high volume dates
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2019-01-31', 165.60, 166.69, 77233600);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2018-10-31', 155.00, 151.79, 60101300);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('FB', '2018-12-19', 141.21, 133.24, 57404900);

-- Google stocks > 1250
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('GOOGL', '2019-04-22', 1236.67, 1253.76, 954200);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('GOOGL', '2019-04-23', 1256.64, 1270.59, 1593400);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('GOOGL', '2019-04-24', 1270.59, 1260.05, 1169800);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('GOOGL', '2019-04-25', 1270.30, 1267.34, 1567200);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('GOOGL', '2019-04-26', 1273.38, 1277.42, 1361400);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('GOOGL', '2019-04-29', 1280.51, 1296.20, 3618400);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('GOOGL', '2019-10-17', 1251.40, 1252.80, 1047900);

-- Google other data
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('GOOGL', '2019-03-15', 1190.30, 1184.46, 2457700);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('GOOGL', '2019-06-10', 1072.98, 1080.38, 1486900);

-- Netflix lowest close prices
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('NFLX', '2018-12-24', 242.00, 233.88, 9547600);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('NFLX', '2018-12-21', 263.83, 246.39, 21397600);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('NFLX', '2018-12-26', 233.92, 253.67, 14402700);

-- Netflix other data
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('NFLX', '2019-06-10', 355.36, 362.44, 8640600);
MERGE INTO stock (st_code, st_date, st_open, st_close, st_volume) KEY(st_code, st_date) VALUES ('NFLX', '2019-09-03', 292.79, 290.89, 5765300);

-- Book data
MERGE INTO book (title, author, isbn) KEY(isbn) VALUES ('Spring in Action', 'Craig Walls', '978-1617294945');
MERGE INTO book (title, author, isbn) KEY(isbn) VALUES ('Clean Code', 'Robert Martin', '978-0132350884');
MERGE INTO book (title, author, isbn) KEY(isbn) VALUES ('Effective Java', 'Joshua Bloch', '978-0134685991');
